### PR TITLE
Make detection of directories compliant with rfc4918

### LINKED ISSUE #53: listContents with recursive=true does not work
Hi,
I'm using the WebDAV adapter to recursively list the contents of an ownCloud server. However, I receive only the files and directories on the first level of the search path.

From looking at the source code (line 283 in WebDAVAdapter.php) it appears that param _recursive_ is not evaluated and _propFind_ is always called with param "1".  According to http://webdav.org/specs/rfc4918.html#HEADER_Depth the correct value should be "infinity".

A quick hack on my side seems to support this assumption. Can you take a look at that?

And by the way: Thanks a lot for providing this very useful package!

### PR DESCRIPTION
**Pull request by kesselb**
Fix #53

### CODE REVIEW

File: src/WebDAVAdapter.php [hunk 1]
```diff
@@ -400,8 +401,18 @@ protected function normalizeObject(array $object, $path)
         return $result;
     }
 
+    /**
+     * @param array $object
+     * @return bool
+     */
     protected function isDirectory(array $object)
     {
-        return isset($object['{DAV:}iscollection']) && $object['{DAV:}iscollection'] === '1';
```
Comment (frankdejonge) [inline src/WebDAVAdapter.php]: wouldn't it make more sense to default to the current implementation instead of returning false in this case?

Comment (kesselb) [reply src/WebDAVAdapter.php]: A good question :thinking: `{DAV:}iscollection` is part of [Web Distributed Authoring and Versioning (WebDAV) Protocol: Microsoft Extensions](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-wdvme/6d81c2e3-9893-4c1d-9e57-4d2345c625f2). Microsoft Extensions sounds like WebDav + additional features from Microsoft.

> Specifies the Web Distributed Authoring and Versioning (WebDAV) Protocol: Microsoft Extensions, which extends the WebDAV Protocol specified in [RFC2518] to extend the standard Hypertext Transfer Protocol (HTTP) mechanisms specified in [RFC2616] for providing file access and content management over the Internet.

As described on [this page](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-wdvme/8cafdf55-ee5c-443e-bdb7-2cb2ab1fb2c3) MS-WDVME extends [RFC2518](https://tools.ietf.org/html/rfc2518) and `{DAV:}resourcetype` is not part of it but RFC2518 has been replaced by [RFC4918](https://tools.ietf.org/html/rfc4918). I would assume that `{DAV:}resourcetype` work with sharepoint but can't test. 

> wouldn't it make more sense to default to the current implementation instead of returning false in this case?

I would say no. We can still add a `MicrosoftWebDAVAdapter` if people are asking for it. What do you think?

Comment (kesselb) [reply src/WebDAVAdapter.php]: @frankdejonge  Please let me know if there's anything we need to change.

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: With Nextcloud and Flysystem and flysystem-webdav, the implementation do not work anymore.
It may start with Microsoft, but is now used in many implementations.

Comment (kesselb) [reply src/WebDAVAdapter.php]: Could you elaborate? Are you voting against this change because other implementations started to adopt this?

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: At least yes, if this is possible. I'm with frankdejonge on this.
Is there no possibility to get it backward compatible to 1.0.5 (my last working version)?

Comment (kesselb) [reply src/WebDAVAdapter.php]: If you apply this patch it's not possible to mount a webdav storage provided by nextcloud? I doubt that because my motivation for this change was this ticket at nextcloud: https://github.com/nextcloud/server/issues/16267

Nextcloud does not support `iscollection`. I see your point but webdav is rfc4918. Take a look at https://github.com/thephpleague/flysystem-webdav/pull/56. I've added some tests against a real webdav server. Tests are failing because the directory detection is not compliant with rfc4918.

I'm fine if you don't want this change. You have to care about the users and breaking existing installations should be avoided.

Comment (kesselb) [reply src/WebDAVAdapter.php]: @JanFischer2 https://github.com/thephpleague/flysystem-webdav/compare/1.0.5...1.0.6 if 1.0.5 is the latest working version than it's exactly the `iscollection` change (which has been released with 1.0.6) that breaks your setup. So you should actually vote for this ;)

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: Ah ok. Now i understand. No vote so far.
Ok I will have a deeper look in my nextcloud<->flysystem communication.

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: Yes you are right an I did not read well enough.
Or better, I still thought in the wrong way.
This change works fine.
Thank you and have a nice weekend :)

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: So now the second part make more sence to me.
Do somebody have a share point webdav?
Does share point provide both attributes or just iscollection?

Cant you still request iscollection and resourcetype?
If its iscollection not set, you can check for resourcetype.

Comment (kesselb) [reply src/WebDAVAdapter.php]: > Cant you still request iscollection and resourcetype?

Yes but `iscollection` is not a part of rfc4918. The proper way to check for a directory is `resourcetype`. I added an example how to keep support for the Microsoft stuff. If someone needs it he can easly adopt it. There is no way to setup a share point instance for testing (so no automated tests). Right now there is only one attribute of this [MS-WDVME](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-wdvme/8cafdf55-ee5c-443e-bdb7-2cb2ab1fb2c3) supported but there is more. Look we needed jquery for years because browser vendors were not able (or willing) to keep their products inter operable.

Comment (JanFischer2) [reply src/WebDAVAdapter.php]: Yeah. I fully agree with you. 
Thats the old web implementation point; especially IE.
The other site is, that it is as it is.
I had this disusion on my oown and with other, many times ;)
May be do it the correct way, but if has no resourcetype, check iscollection.
Its not the fault of the user, what microsoft has done.
But only as idea from me.

Comment (kesselb) [reply src/WebDAVAdapter.php]: Fine by me.
